(define (problem roblocks-roomom)
(:domain blocks-room)
(:objects rooma roomb ball1 ball2)
(:init (room rooma)
(room roomb)
(ball ball1)
(ball ball2)
(position rooma)
(faka)
(at ball1 rooma)
(at ball2 rooma))
(:goal (and (at ball1 roomb) (at ball2 roomb))))