(define (problem room)
(:domain blocks-room)
(:objects roomLeft roomRight a b c d e f)
(:init (clear a) (clear c) (clear d) (clear f)
(ontable b) (ontable c) (ontable d) (ontable e)
(block a) (block b) (block c) (block d) (block e) (block f)
(room roomLeft) (room roomRight) 
(gripper roomLeft) 
(faka) 
(at a roomLeft) (at b roomLeft) (at c roomLeft) 
(at d roomRight) (at e roomRight) (at f roomRight)
(on a b) (on f e))
(:goal (and (at d roomLeft) (at e roomLeft) (at f roomLeft) 
(at a roomRight) (at b roomRight) (at c roomRight) 
(on e f) (on d e) (on b c) (on a b)  
(ontable f) (ontable c))))