(define (problem room)
(:domain blocks-room)
(:objects rooma roomb ball1 ball2)
(:init (room rooma)
(clear ball1)
(clear ball2)
(ontable ball1)
(ontable ball2)
(room roomb)
(ball ball1)
(ball ball2)
(position rooma)
(faka)
(at ball1 rooma)
(at ball2 rooma))
(:goal (and (at ball1 roomb) (at ball2 roomb) (on ball1 ball2))))